-- begin MUZEY_ARCHAEOLOGIST
alter table MUZEY_ARCHAEOLOGIST add constraint FK_MUZEY_ARCHAEOLOGIST_ON_UNIVERSITY foreign key (UNIVERSITY_ID) references MUZEY_UNIVERSITY(ID)^
create index IDX_MUZEY_ARCHAEOLOGIST_ON_UNIVERSITY on MUZEY_ARCHAEOLOGIST (UNIVERSITY_ID)^
-- end MUZEY_ARCHAEOLOGIST
-- begin MUZEY_EXHIBIT
alter table MUZEY_EXHIBIT add constraint FK_MUZEY_EXHIBIT_ON_PLACE foreign key (PLACE_ID) references MUZEY_PLACE(ID)^
alter table MUZEY_EXHIBIT add constraint FK_MUZEY_EXHIBIT_ON_ERA foreign key (ERA_ID) references MUZEY_ERA(ID)^
alter table MUZEY_EXHIBIT add constraint FK_MUZEY_EXHIBIT_ON_EXT_TYPE foreign key (EXT_TYPE_ID) references MUZEY_EX_TYPE(ID)^
create index IDX_MUZEY_EXHIBIT_ON_PLACE on MUZEY_EXHIBIT (PLACE_ID)^
create index IDX_MUZEY_EXHIBIT_ON_ERA on MUZEY_EXHIBIT (ERA_ID)^
create index IDX_MUZEY_EXHIBIT_ON_EXT_TYPE on MUZEY_EXHIBIT (EXT_TYPE_ID)^
-- end MUZEY_EXHIBIT
-- begin MUZEY_ERA
alter table MUZEY_ERA add constraint FK_MUZEY_ERA_ON_KIND foreign key (KIND_ID) references MUZEY_KIND_OF_ERA(ID)^
create index IDX_MUZEY_ERA_ON_KIND on MUZEY_ERA (KIND_ID)^
-- end MUZEY_ERA
